name: cats
description: A app to receive random things of cats

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  lint: ^1.8.2
  package_info: ^2.0.2
  device_info: ^2.0.3
  fluttertoast: ^8.0.8
  logger: ^1.1.0
  google_fonts: ^2.2.0
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs